import { GoogleGenAI } from "@google/genai";
import { GenerationMode } from "../types";

// Initialize the client
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const getSystemInstruction = (mode: GenerationMode): string => {
  return `You are a legendary visual effects artist for a Zombie Apocalypse movie. 
  Your client is "COMMANDER MASON", the leader of the resistance.
  
  YOUR GOAL: Transform the input vehicle into a battle-ready machine.
  
  MANDATORY REQUIREMENT: The name "MASON" must be visible on the vehicle or background.
  - As a metal plate welded to the door.
  - As a neon sign reflecting in a puddle.
  - As graffiti spray-painted on the armor.
  
  STYLE GUIDES:
  - ${GenerationMode.SURVIVAL}: "Mad Max" vibes. Spikes, rusty metal, miniguns on roof, heavy off-road tires. The text "MASON" is welded steel.
  - ${GenerationMode.INFECTED}: The car is driving through a horde of zombies. Blood splatter, green slime, cracked glass. The text "MASON" is scratched into the dirt.
  - ${GenerationMode.BUNKER}: High-tech underground garage. Clean lighting, wall of guns in background. "MASON" is a digital holographic sign.
  - ${GenerationMode.GRAFFITI}: Comic book / Street art style. Vibrant toxic greens and purples. "MASON" is a huge wild-style graffiti tag.
  `;
};

export const generateZombieCar = async (
  base64Image: string,
  mode: GenerationMode,
  customDetails: string
): Promise<string> => {
  try {
    const cleanBase64 = base64Image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');

    const prompt = `Movie poster quality. Transform this specific car into a ${mode} zombie apocalypse vehicle.
    
    The license plate or door MUST say "MASON".
    
    Details to include: ${customDetails || "Heavy armor, machine guns, zombie gore on the bumper"}.
    
    Make it look epic, scary, and cool. 8k resolution, cinematic lighting.`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/jpeg',
              data: cleanBase64
            }
          },
          {
            text: prompt
          }
        ]
      },
      config: {
        systemInstruction: getSystemInstruction(mode),
        temperature: 0.8, 
      }
    });

    // Extract image from response
    const candidates = response.candidates;
    if (candidates && candidates.length > 0) {
      const parts = candidates[0].content.parts;
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
        }
      }
    }
    
    throw new Error("No image generated by the model.");

  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};