import { GoogleGenAI } from "@google/genai";
import { GenerationMode } from "../types";

// Load Vite environment variable (browser-safe)
const apiKey = import.meta.env.VITE_GEMINI_API_KEY as string;

if (!apiKey) {
  throw new Error("Missing VITE_GEMINI_API_KEY – check Vercel environment variables.");
}

// Initialize Gemini client
const ai = new GoogleGenAI({ apiKey });

const getSystemInstruction = (mode: GenerationMode): string => {
  return `You are a legendary visual effects artist for a Zombie Apocalypse movie. 
  Your client is "COMMANDER MASON", the leader of the resistance.
  
  YOUR GOAL: Transform the input vehicle into a battle-ready machine.
  
  MANDATORY REQUIREMENT: The name "MASON" must be visible on the vehicle or background.
  - As a metal plate welded to the door.
  - As a neon sign reflecting in a puddle.
  - As graffiti spray-painted on the armor.
  
  MODE: ${mode.toUpperCase()}
  - "apocalypse" → More spikes, armor, weapons, chaos
  - "neon" → Bright neon lights, cyberpunk, energy
  - "military" → Heavy plating, real weapons, realistic details

  The final output must resemble a highly detailed, cinematic movie still.`;
};

export const createZombieVehicle = async (
  baseImage: string,
  mode: GenerationMode
): Promise<string> => {
  try {
    const instruction = getSystemInstruction(mode);

    const model = ai.getGenerativeModel({
      model: "gemini-2.0-flash-exp",
      generationConfig: {
        temperature: 0.9,
        maxOutputTokens: 2048,
      },
    });

    const result = await model.generateContent([
      {
        role: "user",
        parts: [
          { text: instruction },
          {
            inlineData: {
              data: baseImage.split(",")[1],
              mimeType: "image/jpeg",
            },
          },
        ],
      },
    ]);

    const output = await result.response;
    const candidates = output.candidates;

    if (!candidates || candidates.length === 0) {
      throw new Error("No response from Gemini.");
    }

    if (candidates[0].content.parts) {
      const parts = candidates[0].content.parts;
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:${part.inlineData.mimeType || "image/png"};base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error("No image generated by the model.");
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};
